apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-test-config
data:
  APP_VERSION: "1.0.0"
  APP_ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: k8s-test-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: k8s-test-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-test-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-test-app
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-test-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-test-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-test-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-test-role
subjects:
- kind: ServiceAccount
  name: k8s-test-sa
  namespace: default
