apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-app-green
  labels:
    app: k8s-test-app
    version: green
spec:
  replicas: 1  # Changed from 3 to 1 to match blue deployment
  selector:
    matchLabels:
      app: k8s-test-app
      version: green
  template:
    metadata:
      labels:
        app: k8s-test-app
        version: green
    spec:
      containers:
      - name: k8s-test-app
        image: localhost:32000/k8s-test-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: APP_VERSION
          value: "1.1.0"
        - name: APP_ENVIRONMENT
          value: "production"
        - name: DEPLOYMENT_VERSION
          value: "green"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: k8s-test-secret
              key: secret-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-test-service-green
  labels:
    app: k8s-test-app
    version: green
spec:
  selector:
    app: k8s-test-app
    version: green
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer  # Changed from ClusterIP to LoadBalancer for MetalLB
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-test-hpa-green
  labels:
    app: k8s-test-app
    version: green
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-test-app-green
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
