apiVersion: v1
kind: Service
metadata:
  name: k8s-test-metrics
  labels:
    app: k8s-test-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: k8s-test-app
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-test-monitor
  labels:
    app: k8s-test-app
spec:
  selector:
    matchLabels:
      app: k8s-test-app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k8s-test-alerts
  labels:
    app: k8s-test-app
spec:
  groups:
  - name: k8s-test-app.rules
    rules:
    - alert: K8sTestAppDown
      expr: up{job="k8s-test-app"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "K8s Test App is down"
        description: "K8s Test App has been down for more than 5 minutes."
    
    - alert: K8sTestAppHighCPU
      expr: rate(cpu_usage_seconds_total{job="k8s-test-app"}[5m]) > 0.8
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "K8s Test App high CPU usage"
        description: "K8s Test App CPU usage is above 80% for more than 10 minutes."
    
    - alert: K8sTestAppHighMemory
      expr: memory_usage_bytes{job="k8s-test-app"} / memory_limit_bytes{job="k8s-test-app"} > 0.9
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "K8s Test App high memory usage"
        description: "K8s Test App memory usage is above 90% for more than 10 minutes."
    
    - alert: K8sTestAppHighErrorRate
      expr: rate(http_requests_total{job="k8s-test-app",status_code=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "K8s Test App high error rate"
        description: "K8s Test App error rate is above 10% for more than 5 minutes."
